nome=input('Olá amigo(a)! como você se chama? ')
print('Que belo nome! Muito prazer em te conhecer {}! Meu nome é Rex!'.format(nome))
idade=input('Quantos anos você tem? ')
print('Nossa, quanta experiência né? Hahaha. Eu tenho 74 anos. ')
conta=input('quero praticar minha matemática... Você pode me ajudar? ')
sub=int(74)-int(idade)
print=input('Fiz as contas aqui, nossa diferença de idade é de {}. Correto? '.format(sub))
print=input('Hahahaha, o pai tá online! Valeu {}, foi um prazer te conhecer. Até mais!'.format(nome))
